services:
  - type: web
    name: stocker-ai
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      bash setup.sh
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
